### ISSUE TITLE
Canonical Telegram Hubot Adapter

### ISSUE THREAD

**Issue by arcturial** [lukefx/hubot-telegram#1]
Hey

With regards to https://github.com/github/hubot/pull/993, do you want to merge your code with mine or how do you want to go about doing this? I would like to make use of the telegrambot npm module instead of doing the HTTP directly in the Hubot adapter. This will help with future extendibility. I am also in the progress of adding different message types like "Leave" and "Join".

**Comment by lukefx** [comment]
Hey! I'm absolutely ok with the idea to merge the two projects, for me it's the same if you want I could give you full access to my repo and use hubot-adapter as name for the lib. 
Meanwhile I'm proposing some api changes to hubot for support a native way to send back images, video or audio.

**Comment by arcturial** [comment]
So are you ok with using the telegrambot library, I think it will be valuable especially in the case where we start doing things like sending raw images. It's easier to keep error management and API response management all in once place that can be reused for other projects. If yes, then I can merge my code into your repository, or I can update it my side to use the "hubot-telegram" npm package name.

**Comment by arcturial** [comment]
would it be possible to get access to the repository so I can clone and push directly instead of creating a fork?

**Comment by lukefx** [comment]
Done :)

**Comment by arcturial** [comment]
Pretty much done with the merger.

https://github.com/lukefx/hubot-telegram/tree/feature-arcturial-merge

Have a look in the merger branch and let me know if you agree with the changes etc. You can also test it in your hubot by using the following in your package.json:

"hubot-telegram": "https://github.com/lukefx/hubot-telegram.git#feature-arcturial-merge"

**Comment by arcturial** [comment]
Shall I go ahead and merge these?

**Comment by lukefx** [comment]
Hey, for me it's ok. Just merge it. My only concern is that the api are really easy and keep only one file in another npm module is...more than needed. I would include telegrambot directly in the main repo.
When you have some spare time just have a look at my experimental branch:  https://github.com/lukefx/hubot-telegram/compare/experimental

**Comment by arcturial** [comment]
Don't you think it's better to keep it separated for the sake of re-usability. Someone might need to interact with telegram without using the Hubot adapter. If you keep the API interaction code on it's own, they can use that library without having the extra code meant for Hubot only. Essentially the api.coffee file you created can be used in any scenario where a user wants to interact with a Telegram bot.

**Comment by arcturial** [comment]
I merged the changes to master, can you perhaps bump the revision on NPM so we can close this issue. I will have a look at the experimental changes as part of a separate ticket. Also, any way to grant me access to that one NPM package?

**Comment by arcturial** [comment]
`npm owner add <user> <package name>`

Looks like it is possible

**Comment by lukefx** [comment]
Yepp, I've added you as npm owner...
