### ISSUE TITLE
Username handling

### ISSUE THREAD

**Issue by idmit** [lukefx/hubot-telegram#14]
I tried some packages which require mentioning people in a room, and they don't work.

Is it possible to get usernames from telegram API to hubot?

**Comment by arcturial** [comment]
The usernames are already part of the `message` variable and is not adapter specific, can you maybe list the package you tried so I can try and replicate the issue?

**Comment by idmit** [comment]
The package is [hubot-ambush](https://github.com/hubot-scripts/hubot-ambush).

It uses `robot.brain.usersForFuzzyName` search and it feels like with telegram it tries to match items in list of ids not names. So I thought maybe telegram adapter doesn't handle its part correctly :blush:

**Comment by arcturial** [comment]
cool, will see what I can figure out

**Comment by arcturial** [comment]
Do you have to `hubot-redis-brain` script enabled so that your data is persisted? It will work without that, but then you need to make sure that user in question has at least sent one message to Hubot so that it's information is in memory. Without persistence it also means that you will lose all user data after each restart and all users will have to ping Hubot at least once before they become available in the lookup list.

**Comment by idmit** [comment]
How do I check if it's working? Hubot says
```
INFO hubot-redis-brain: Using default redis on localhost:6379
```
on startup.

**Comment by arcturial** [comment]
Are you using Heroku?

**Comment by idmit** [comment]
My hubot is living on DigitalOcean droplet.

**Comment by arcturial** [comment]
Haven't worked with that platform yet, but first I would make sure I have a Redis instance running. They should provide some sort of Redis service I would presume. If you are sure Redis is already running (and from the looks of it it might be) you can test it with a custom hubot script by doing this:

`console.log(@robot.brain.users)`

or if you aren't using coffeescript

`console.log(robot.brain.users)`

If persistence is working, this should dump a list of all the users recognized by Hubot...if this list is empty after every reset (after your previously spoke to Hubot) then your persistence is definately not working.

**Comment by idmit** [comment]
You were right my redis wasn't running. Now all is ok, but bot reacts only when you mention it,we discussed it earlier considering privacy settings.

**Comment by idmit** [comment]
Again, thanks a lot! :+1: :blush:
