### ISSUE TITLE
extending to allow sending of stickers etc.

### ISSUE THREAD

**Issue by dcsan** [lukefx/hubot-telegram#15]
can you give some guidance how to extend this API to send stickers?
i'm looking at the way other APIs are called:

https://github.com/lukefx/hubot-telegram/blob/master/src/telegram.coffee#L94
```coffee
    send: (envelope, strings...) ->
        self = @
        @api.invoke 'sendMessage', { chat_id: envelope.room, text: strings.join() }, (err, message) =>
```

so then this part would be easy enough to extend as 
https://core.telegram.org/bots/api#sendsticker

        @api.invoke 'sendSticker', { chat_id: envelope.room, sticker: "someFileId" }

but how do i tell Hubot to understand how to connect to this non-standard adapter message?

I tried with a script as 

```
  robot.hear /sticker/i, (res) ->
    res.sendSticker "sticker!"
```

but get the beloved: `undefined is not a function`

UPDATE
I see a readme in the node_module that doesn't seem to be in the repo itself...

```
## Available Methods

All methods available on the API can be access using this library. The list of methods and expected results can be found in the [Bot API document](https://core.telegram.org/bots/api).

The methods can be used like this:

``` nodejs
var TelegramBot = require('telegrambot');
...
api.sendSticker(opts, callback);


```

so is an `api` object available to the scripts?

**Comment by dcsan** [comment]
https://github.com/github/hubot/pull/996#issuecomment-133635032

oh ok it seems you can't just add new methods for a custom adapter, you have to stick with what's lowest common denominator? well, that scratches hubot for me >.<

**Comment by arcturial** [comment]
Yeah, this is unfortunate...but I think they are trying to be platform agnostic and thus can only support the basics across all. You can still use Hubot, but then you will need to add your own custom functionality to the specific adapter you will be using and the specific scripts that will utilize it. This means you will be locked in to that specific vendor/adapter unfortunately.

**Comment by dcsan** [comment]
OK thanks for the comments. I thought i was just being dense not seeing how to extend it, I'm surprised that's by design. for now it was more trouble than benefit to use hubot.

**Comment by technicalpickles** [comment]
To be clear, we (hubot maintainers) are open to improvements to make hubot's experience on different adapters better. The hard part is balancing support for all the existing hubots out there that aren't using an chat service that is as rich as, say, telegram. I hope the discussion after https://github.com/github/hubot/pull/996#issuecomment-133635032 reflects that.
