### ISSUE TITLE
Request: better room data?

### ISSUE THREAD

**Issue by rubybrowncoat** [lukefx/hubot-telegram#18]
Would it be possible to expand the normal msg.message.room (for telegram it is really just a number and barely useful) information in some (probably convoluted) way?

**Comment by arcturial** [comment]
What did you have a in mind? The room variable currently contains the "chat_id" that Telegram returns. 

Might be possible to include some values that are returned in the message object https://core.telegram.org/bots/api#message.

**Comment by rubybrowncoat** [comment]
Maybe add the contents of the chat property, so that when the room is just an id (as is the case with telegram) we can get some additional data from the chat property.

**Comment by arcturial** [comment]
The user object will contain another key called `telegram_chat` in addition to the `room` value.

https://github.com/lukefx/hubot-telegram/pull/37
