### ISSUE TITLE
User username change/addition problem?

### ISSUE THREAD

**Issue by rubybrowncoat** [lukefx/hubot-telegram#19]
Users that change or add a username still have either their id or their old username in the msg.message.user properties.

Is this a problem with the telegram api?

**Comment by arcturial** [comment]
This is probably due to stale data being stored in the robot brain. I will have a look at this.

**Comment by arcturial** [comment]
Hey

Please have a look at https://github.com/lukefx/hubot-telegram/tree/issue-19

You can try it out in your hubot by changing package.json to:

```
"hubot-telegram": "lukefx/hubot-telegram#issue-19"
```

The change I made will regenerate the user cache for a specific user if the users first name or surname changes.

**Comment by arcturial** [comment]
Resolved with merge https://github.com/lukefx/hubot-telegram/commit/b1f55e8a452118e0865cde0f6341ebed21db5574

**Comment by rubybrowncoat** [comment]
I haven't had time to test this change, I have only skimmed the code changes, and probably won't have time for a few more days. I have a question and it may be a stupid one given the caveats before: all looks good when first name or last name changes, but what happens when the username changes from either empty to something or from something to something else?

**Comment by arcturial** [comment]
This is a bit embarrassing, but I only realized you can change the username this weekend after I merged the changes XD I will modify the code to also include the ability to change the username. Very silly oversight.
