### ISSUE TITLE
[help wanted] How to use telegram specific functionality

### ISSUE THREAD

**Issue by Winor** [lukefx/hubot-telegram#21]
Hi, I can't understand how to use telegram specific functionality using the example on the readme, It would be great if someone can create a working coffee script (which sends a picture or a sticker) so I can learn from it. sorry for being such a noob :sweat_smile: 
Thanks.

**Comment by arcturial** [comment]
Hi

Have a look at the https://github.com/lukefx/hubot-telegram/tree/issue-21 branch. It contains an `example/` folder with a script that can be used to deliver an image to a user.

**Comment by Winor** [comment]
Thanks for your reply, I've tried to use this script but the bot won't send any photo to chat and no log appears on console.

**Comment by arcturial** [comment]
Are you addressing the bot directly or in a group chat?

**Comment by Winor** [comment]
I've tried to address the bot both ways but no luck

**Comment by arcturial** [comment]
can you perhaps provide me with your bots name so I can try it?

**Comment by Winor** [comment]
my bot name is @Win0bot

**Comment by arcturial** [comment]
Did you put the script in the `scripts` folder? Try adding a console.log command to the script when it initializes, to see if its actually registering with Hubot.

**Comment by arcturial** [comment]
You should be seeing this in the logs (if you are running with DEBUG on).

`DEBUG Message `send photo' matched regex //send photo/i/`

If you don't see this, the script is probably not loaded by Hubot.

**Comment by Winor** [comment]
the script is inside the scripts folder and it's loaded, the bot running with debug on and I can see this message on log, but it doesn't send any photo.

**Comment by arcturial** [comment]
What version of the telegram adapter are you using? The `telegram:invoke` event is currently only available in the master branch and has not been tagged yet.

You can include this version in your package file like so:

`"hubot-telegram": "lukefx/hubot-telegram#master"`

**Comment by Winor** [comment]
oh, I wanna kill myself right now. I thought I was using the master branch. it works now.
Thank you so much , I really appreciate your work !

**Comment by arcturial** [comment]
no problem ;)

I will tag the master branch soon then you can use the normal version constraints again.
