### ISSUE TITLE
group chat response

### ISSUE THREAD

**Issue by Gooogole** [lukefx/hubot-telegram#27]
input /help in the chat with my bot, it working well.
when input /help in the group with my bot
i can see the log：INFO Receiving message_id: 91
but it doesn't sending message to room: xxxxxxx, where is wrong?

**Comment by Gooogole** [comment]
from your code i found the result；
# If it is a private chat, automatically prepend the bot name if it does not exist already.
so in the group must add botname。

**Comment by psamim** [comment]
@Gooogole I have the same problem, what did you do? How do you mention your bot? What is the alias?
Thanks

**Comment by arcturial** [comment]
In a group chat, the bot should respond to messages like these:

- All messages that start with a slash ‘/’ (see Commands above)
- Messages that @mention the bot by username
- Replies to the bot's own messages
- Service messages (people added or removed from the group, etc.)

If private mode has been disabled, it will react to all messages.

What message are you sending and are you using the chat with private mode disabled?

**Comment by unlucio** [comment]
Sorry guys I'm having the same issue: invited to a group the bot shows up fine and I can see the `INFO Receiving message_id: ##` logs for every mention/command but the bot never outputs anything to the group.
It works fine in DM tho.

`setjoingroups` is enable and I tried with `setprivacy` both enabled and disabled but nothing changes.

Any suggestion?

**Comment by arcturial** [comment]
If you run the bot in debug mode, it will output the exact message it receives. Can you paste that message here please?

**Comment by unlucio** [comment]
I found the problem: it doesn't like names containing `_` (underscore) characters :/

**Comment by arcturial** [comment]
Interesting, can you please log a new bug report with this problem. Will try and address it as soon as possible.
