### ISSUE TITLE
x.509 self-signed certificate

### ISSUE THREAD

**Issue by aliasfalse** [lukefx/hubot-telegram#29]
Wanted to see if there was a way to add a self-signed certificate, since telegram only communicates fully over https. I'm collaborating with a team that is looking at options to move an existing bot to interface with hubot so that it can be more easily used on different chat platforms.

Does something like this exist for hubot-telegram?

**Comment by arcturial** [comment]
This ticket has been answered in https://github.com/lukefx/hubot-telegram/issues/30
