### ISSUE TITLE
Bot doesn't answer to @name messages

### ISSUE THREAD

**Issue by rubybrowncoat** [lukefx/hubot-telegram#3]
Somehow, with the new feature merge, the bot started with `bin/hubot -a telegram -n CoolNameBot -l CoolBotName` doesn't answer to @CoolNameBot anymore, only to @CoolBotName, CoolBotName  or CoolNameBot queries.

Doesn't react when the @ is prepended to its name.

**Comment by arcturial** [comment]
I think this has to do with the regex added to remove redundant characters when a bot is addressed in private mode. May I ask, what is you bot called in Telegram?

**Comment by rubybrowncoat** [comment]
Following the previous example, the username of the bot would be CoolNameBot. So that name and telegram username match and telegram autocompletion can help with interacting with the bot.

**Comment by arcturial** [comment]
That is the part that is breaking it. The regex strips out any mention of the Telegram Bot name even if it's the same as the Hubot name. I will push an update tonight that leaves the name in tact if it's the same as the Hubot name.

Example:

@CoolNameBot ship it
- acceptable

@CoolNameBot, CoolNameBot ship it
- still acceptable (the first part is the Telegram Bot privacy mode mention)

@TelegramCoolNameBot, CoolNameBot ship it
- not acceptable, should be transformed to CoolNameBot ship it

**Comment by rubybrowncoat** [comment]
Thank you.

One more thing, the bot in question is not running in privacy mode. So that's something to consider.

**Comment by arcturial** [comment]
It use to be a configuration value you have to pass, but that seemed redundant. In general the code will try and remove the name of the Telegram bot when it doesn't fit with the Hubot. I will try some things and see if that works, otherwise I might make it a configuration value again.

**Comment by arcturial** [comment]
Do you think it that I should perhaps stop the adapter from loading if the Hubot name is not the same as the bot name in Telegram? Or perhaps display a warning of sorts.

I can go and add all sort of magic to strip out the name if it's different to the Hubot name or to remove the Hubot name if it appears alongside the Telegram name in a sentence, but this might just lead to more undesired behaviour. I feel it might perhaps be best to leave any @[mention] in the string and just suggest to the user that the names of the Telegram Bot and Hubot should be the same or you might have a bad user experience. What do you think?

**Comment by rubybrowncoat** [comment]
I think the mentions have their place as most hubot commands respond to name requests. They appear to be part of hubot design.

To me that means that it makes absolute sense that the bot name and the telegram bot username coincide, even if only for autocompletion purposes. But other users might not feel the same way about it. Maybe a warning would be more appropriate in this case.

Regardless I would avoid removing mentions from messages as some scripts seem to rely on them.

**Comment by arcturial** [comment]
https://github.com/lukefx/hubot-telegram/pull/6

I removed the code that strips out any mentions, please try the master branch and let me know if this works for your setup.

**Comment by rubybrowncoat** [comment]
Appear to be working correctly.
