### ISSUE TITLE
Request: Change default endpoint for webhooks

### ISSUE THREAD

**Issue by nspacestd** [lukefx/hubot-telegram#30]
Telegram recommends using a secret webhook endpoint, such as `https://www.example.com/<token>` for security reasons. Would it be possible to implement something like that?

**Comment by arcturial** [comment]
The default endpoint URL is currently based on the PORT your bot runs with. You can start the bot on the secure port by passing the PORT or EXPRESS_PORT environment variable to hubot when it starts. 

Unfortunately, adding certificates is a bit difficult. Hubot is tracking the issue with SSL in it's main repository https://github.com/github/hubot/issues/727. It seems that Hubot doesn't have all the features of a normal web server.

You can get around this by creating your own Hubot script that starts your own server on the port (with certificates) of your choice and just pass the incoming messages to the `robot.adapter` object.

You can then configure the adapter endpoing using the TELEGRAM_WEBHOOK environment variable and specifying your custom endpoint.

The other alternative is to use the TELEGRAM_INTERVAL environment variable and set a low polling interval of 1000 milliseconds or so. This way you don't have to worry about HTTPS.

**Comment by nspacestd** [comment]
My question was actually about using a secret endpoint (i.e. one that only Telegram servers know about) rather than a secure one (i.e. encrypted with SSL). Right now the adapter listens for POST requests to `/hubot/telegram/receive`, but Telegram currently provides no way to make sure these are actually coming from their servers and not from other sources, so they suggest using a secret endpoint, such as one that has the bot token in its path.

**Comment by arcturial** [comment]
My apologies. It's definitely possible. I will have a look at adding the token into the default endpoint path or perhaps offering another environment variable that can be set to support backwards compatibility. Might be best to just make the endpoint secret by default and people with new versions should just update their endpoint.
