### ISSUE TITLE
Telegram's extra options should be always strings

### ISSUE THREAD

**Issue by lukefx** [lukefx/hubot-telegram#42]
Not a real issue but just an important thing, while sending messages to channels without a response or hear, all extra parameters should be strings or it will cause an exception.

Example:

```
post_to_channel = (message) ->
  envelope =
    room: "@mychannel"
    telegram:
      reply_markup: "Markdown"
      disable_web_page_preview: 'true'
  robot.send envelope, message
```

We can't use `disable_web_page_preview: true`

Could we modify the `applyExtraOptions` function to encode extra params to strings?

**Comment by arcturial** [comment]
Hey, please review https://github.com/lukefx/hubot-telegram/pull/48

**Comment by arcturial** [comment]
This started working for me without the "toString" casting. You still having issues on  your side?

**Comment by lukefx** [comment]
#52 and #54 address this issue...closing it
