### ISSUE TITLE
bot no receiving messages from supergroup

### ISSUE THREAD

**Issue by elopio** [lukefx/hubot-telegram#47]
I have a hubot bot with this telegram backend ( https://github.com/jaquerespeis/eljaqueado )
Today we migrated our group chat to a supergroup, and now the bot is not receiving any messages from the group. Direct message still work fine.

**Comment by arcturial** [comment]
I too have experienced this issue, I will investigate it and update as soon as possible.

**Comment by arcturial** [comment]
Do you see anything in the bot log when sending messages to a supergroup? Does it look like it's receiving, but just not processing?

**Comment by elopio** [comment]
I have HUBOT_LOG_LEVEL=debug, and it just doesn't print anything.

**Comment by arcturial** [comment]
Hi, the latest master version has some more debug added to the update method. Can you please try it and let me know if and JSON content gets dumped when you send a message. If the message doesn't appear in the log, it means the Bot API is not picking it up. If this is the case, it could be that your group is in private mode and you need to address the bot differently.

**Comment by elopio** [comment]
thanks for your help. Nothing appeared after updating the module. I created a new super group and it worked, so I was puzzled. 
Then @rngkll suggested to add the bot again to the channel, and that worked. So I'm guessing that for some reason, the bot was kicked out when the channel was turned into a supergroup. I think there is no bug in the adapter, so I'm closing this.
