### ISSUE TITLE
Private messages problem

### ISSUE THREAD

**Issue by rubybrowncoat** [lukefx/hubot-telegram#5]
Bot treats private message as public messages and requires name prepending for all commands that require it. Normal hubot behaviour (from Slack, that is my experience) is that private message do not require name prepending.

Is there a way to distinguish between group and private messages?

**Comment by arcturial** [comment]
Is there a particular command that is causing a problem? For example, the "ship it" command works for me without mentioning the bot name. However, "pug me" requires that I mention the bot name.

**Comment by rubybrowncoat** [comment]
All commands should work in private without mention. Ship it works because it works without mention everywhere (robot.hear).

All commands that require mention (robot.respond) in public chatrooms shouldn't require it in private.

**Comment by arcturial** [comment]
I see what you mean, it seems like the Slack adapter automatically adds the bot name when you are chatting one on one. This is a nifty feature, I will see if it's possible to determine if a chat is one on one with the Telegram API and then add it to the adapter.

**Comment by lukefx** [comment]
https://github.com/lukefx/hubot-telegram/commit/a922453803e919fffb25cacf2630dac5084ce1b1#diff-4912156bdc31f7d9e3344142d6609d2aR48

The bot does it, but in the merge of the two projects we lost that feature. User id are always positive, rooms are negative.

**Comment by arcturial** [comment]
I am in the process of restoring it, will make it a bit more robust so you don't end up with a scenario like `hubot hubot pug me`

**Comment by lukefx** [comment]
:+1:

**Comment by arcturial** [comment]
Please review https://github.com/lukefx/hubot-telegram/tree/fix-bot-private, this should take care of the private chat scenario.

**Comment by lukefx** [comment]
Hey, perfect... :shipit:

**Comment by rubybrowncoat** [comment]
Let's use the example from the other issue: `bin/hubot -a telegram -n CoolNameBot -l CoolBotName`.

The bot now answers correctly on:
`command` (name omitted)
`CoolNameBot command` (name)

It however fails on fringe cases like:
`@CoolNameBot command` (mention with @)
`coolnamebot command` (case-insensitive name)
`@coolnamebot command` (case-insensitive mention with @)
`CoolBotName command` (alias)
`coolbotname command` (case-insensitive alias)

**Comment by arcturial** [comment]
Cool, I will have a look at those ones later today. You are welcome to submit a PR if you manage to fix it in the meanwhile. I would suggest adding the logic for pre-pending the name into a private function, then I will set up some mocha tests so we can get some tests going for the project.

**Comment by arcturial** [comment]
Please have a look at the branch https://github.com/lukefx/hubot-telegram/tree/feature-issue-5, I included the scenarios you mentioned along with tests for each of them. 

You can run the tests with `npm test`.

@lukefx can you perhaps configure a http://travis-ci.org build for us? I don't seem to have access to this repository from my travis account.

**Comment by rubybrowncoat** [comment]
I'm testing now and while tests are working correctly, the bot now answers correctly only on:
`command` (name omitted)

**Comment by arcturial** [comment]
It is a work in progress, having a look at the response issues.

**Comment by arcturial** [comment]
Hey, the problem should be fixed now. My regex pattern was wrong, I included the trailing and leading slashes as part of a new RegExp object.

**Comment by arcturial** [comment]
Merged the branch with master and removed it, the scenarios provided above works for me now.
