### ISSUE TITLE
CoffeeScript 2.x support

### ISSUE THREAD

**Issue by iphoting** [lukefx/hubot-telegram#67]
There are a few breaking changes in 2.x that impacts the telegram adaptor: <https://coffeescript.org/#breaking-changes>.

```
ERROR Cannot load adapter telegram - /app/node_modules/hubot-telegram/src/telegram.coffee:7:10: error: unexpected newline
     super
          ^
```

A potential fix might be to replace `super` with `super()`.

**Comment by lukefx** [comment]
thx @iphoting for notice that... I was thinking of rewrite a new version of the adaptor with plain Javascript since hubot now is also javascript and not coffeescript anymore.

**Comment by lukefx** [comment]
The new version on the develop branch is in Typescript... so this should not be an issue.
